---

- hosts: centos
  become: yes

  tasks:
          - name: get zabbix_agent repository
            yum:
                name: "https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm"

          - name: install zabbix_agent
            yum:
                    name: zabbix-agent
                    state: present

          - name: get postgres reposirory
            yum:
                name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"

          - name: install postgres
            yum:
                    name: postgresql12-server
                    state: present

          - name: initiate postgres data base
            command: >
                    sudo /usr/pgsql-12/bin/postgresql-12-setup initdb

          - name: copy elasticsearch rpm package
            copy:
                    src: /home/ansible-admin/elasticsearch-8.7.0-x86_64.rpm
                    dest: /tmp/elasticsearch-8.7.0-x86_64_ansible_copy.rpm

          - name: install elasticsearch
            yum:
                    name: /tmp/elasticsearch-8.7.0-x86_64_ansible_copy.rpm
                    state: present

          - name: copy kibana rpm package
            copy:
                    src: /home/ansible-admin/kibana-8.7.1-x86_64.rpm
                    dest: /tmp/kibana-8.7.1-x86_64_ansible_copy.rpm

          - name: install kibana
            yum:
                    name: /tmp/kibana-8.7.1-x86_64_ansible_copy.rpm
                    state: present

  handlers:
  - name: zabbix_agent is enabled and running
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started

  - name: postgres is enabled and running
    systemd:
     name: postgresql-12.service
     enabled: yes
     state: started

  - name: elasticsearch is enabled and running
    systemd:
     name: elasticsearch.service
     enabled: yes
     state: started

  - name: kibana is enabled and running
    systemd:
     name: kibana.service
     enabled: yes
     state: started

