---

- hosts: ubuntu
  become: yes

  tasks:
          - name: get zabbix repository
            get_url:
                url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb"
                dest: /home/ansible-admin/
            when:
                    ansible_os_family == "Debian"


          - name: install zabbix repository
            apt:
                    deb: /home/ansible-admin/zabbix-release_6.0-4+ubuntu20.04_all.deb
                    state: present
            when:
                    ansible_os_family == "Debian"


          - name: install zabbix_agent
            apt:
                    name: '{{ item }}'
                    update_cache: yes
            with_items:
                    - zabbix-agent
            when:
                    ansible_os_family == "Debian"


          - name: copy zabbix_agent config
            copy:
                    src: /home/ansible-admin/zabbix_agentd.conf
                    dest: /etc/zabbix/zabbix_agentd.conf
            when:
                    ansible_os_family == "Debian"


          - name: restart zabbix_agent
            service:
                    name: zabbix-agent
                    state: restarted
            when:
                    ansible_os_family == "Debian"

  handlers:
  - name: zabbix_agent is enabled and running
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
